[meta]
app = "btop"
schema = 1
handler = "file"
target = "~/.config/btop/themes"
filename = "current.theme"
dynamic = false

[content]
text = """
theme[main_bg]=#FFF5F5
theme[main_fg]=#2D2D2D
theme[title]=#2D2D2D
theme[hi_fg]=#F57C00
theme[selected_bg]=#F5DADA
theme[selected_fg]=#2D2D2D
theme[inactive_fg]=#757575
theme[graph_text]=#616161
theme[meter_bg]=#F2DDDD
theme[proc_misc]=#7B1FA2
theme[cpu_box]=#00838F
theme[mem_box]=#43A047
theme[net_box]=#0288D1
theme[proc_box]=#7E57C2
theme[div_line]=#EDD0D0

# Temperature graph
theme[temp_start]=#43A047
theme[temp_mid]=#D4A017
theme[temp_end]=#D32F2F

# CPU graph
theme[cpu_start]=#00838F
theme[cpu_mid]=#0277BD
theme[cpu_end]=#7E57C2

# Mem/Disk free meter
theme[free_start]=#D64545
theme[free_mid]=#D4A017
theme[free_end]=#43A047

# Mem/Disk cached meter
theme[cached_start]=#0277BD
theme[cached_mid]=#42A5F5
theme[cached_end]=#0288D1

# Mem/Disk available meter
theme[available_start]=#43A047
theme[available_mid]=#D4A017
theme[available_end]=#E65100

# Mem/Disk used meter
theme[used_start]=#43A047
theme[used_mid]=#E91E63
theme[used_end]=#D64545

# Download graph
theme[download_start]=#43A047
theme[download_mid]=#00838F
theme[download_end]=#42A5F5

# Upload graph
theme[upload_start]=#D64545
theme[upload_mid]=#E91E63
theme[upload_end]=#D4A017

# Process box gradient
theme[process_start]=#f4e3e3
theme[process_mid]=#F2DDDD
theme[process_end]=#a99a9a

# Process list banner
theme[proc_pause_bg]=#F5DADA
theme[proc_follow_bg]=#1976D2
theme[proc_banner_bg]=#E65100
theme[proc_banner_fg]=#2D2D2D
theme[followed_bg]=#F5DADA
theme[followed_fg]=#1976D2

"""
