[meta]
app = "localsend_app"
schema = 1
handler = "settings"
dynamic = false

[settings]
mode = "light"
color = "system"
target = "~/.local/share/org.localsend.localsend_app"
filename = "shared_preferences.json"

